# Generated by Django 4.2 on 2024-06-08 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 6, 8, 15, 4, 47, 298469, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
